[tool.poetry]
name = "sax"
version = "0.1.1"
description = "pure python xml parser"
authors = ["jnpn <johan.ponin.pro@gmail.com>"]
license = "No License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
pytest-coverage = "^0.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
