
* Tokenizer

** DONE add comment support

** DONE add doctype support

** factor saxg code

   most sub generators are the same

** large test, OpenDocument sample (34KB)
   cv.xml

** DONE Bug: cv.xml uncovers an infinite loop in saxg

*** Trace. Warning, 98 lines

  in test_xml_cv
  in xml in root in inst in root in text in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in etag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in otag in root in text in root
  in etag in root in etag in root in otag in root in otag in root in otag in root
  in otag in root in text in root in etag in root in otag in root in otag in root
  in text in root in etag in root in text in root in etag in root in otag in root
  in text in root in etag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in etag in root in otag in root in otag in root
  in otag in root in text in root in etag in root in otag in root in text in root
  in etag in root in etag in root in otag in root in otag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in etag in root in otag in root in otag in root in otag in root
  in text in root in otag in root in text in root in etag in root in etag in root
  in etag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in etag in root in otag in root in etag in root in otag in root
  in otag in root in otag in root in text in root in etag in root in etag in root
  in otag in root in otag in root in text in root in etag in root in otag in root
  in text in root in etag in root in etag in root in otag in root in otag in root
  in otag in root in otag in root in etag in root in otag in root in etag in root
  in otag in root in otag in root in otag in root in text in root in etag in root
  in etag in root in otag in root in otag in root in text in root in etag in root
  in otag in root in text in root in etag in root in etag in root in otag in root
  in otag in root in otag in root in otag in root in etag in root in otag in root
  in etag in root in otag in root in otag in root in otag in root in text in root
  in etag in root in etag in root in otag in root in otag in root in text in root
  in etag in root in otag in root in text in root in etag in root in etag in root
  in otag in root in otag in root in otag in root in otag in root in etag in root
  in otag in root in etag in root in otag in root in otag in root in otag in root
  in text in root in otag in root in text in root in etag in root in text in root
  in otag in root in text in root in etag in root in etag in root in etag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in etag in root in etag in root in otag in root in otag in root
  in otag in root in otag in root in text in root in etag in root in etag in root
  in etag in root in otag in root in otag in root in otag in root in text in root
  in etag in root in otag in root in text in root in etag in root in etag in root
  in otag in root in otag in root in text in root in etag in root in etag in root
  in otag in root in otag in root in otag in root in text in root in etag in root
  in etag in root in etag in root in etag in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in etag in root in etag in root
  in otag in root in otag in root in otag in root in text in root in etag in root
  in etag in root in otag in root in otag in root in text in root in etag in root
  in otag in root in text in root in etag in root in etag in root in otag in root
  in otag in root in otag in root in otag in root in otag in root in etag in root
  in etag in root in otag in root in otag in root in otag in root in text in root
  in etag in root in etag in root in otag in root in otag in root in text in root
  in etag in root in otag in root in text in root in etag in root in otag in root
  in otag in root in text in root in etag in root in etag in root in etag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in etag in root in etag in root in otag in root in otag in root in otag in root
  in text in root in etag in root in etag in root in otag in root in otag in root
  in text in root in etag in root in otag in root in text in root in etag in root
  in otag in root in text in root in etag in root in otag in root in otag in root
  in peek

*** Fix: sys.setrecursionlimit(1800)
    (previously set to 2000, but 1800 is fine here)
    cv.xml prints.

    Strangely, cv.xml is neither that deep:

    @>>> import sys
    @>>> sys.setrecursionlimit(1800)
    @>>> t = xml(root(open('./samples/cv.xml', 'rb')))
    @>>> xmldepth(t)
    11

    Nor that long:

    @>>> len(list(root(open('./samples/cv.xml', 'rb'))))
    988

    Need to rewrite as a single while True: generator ?

** Imperative code : factorization

   text s k =
     acc = zero
     t = read
     while pred(t) and term(t) # or term(peek(s))
       acc <- t
       t <- read

   inclusive or exclusive statements

   k, acc

   # - accumulate until pred
   # - inclusive / exclusive flag
   #   inclusive -> default = post append
   #   exclusive -> default = post rewind
   # - on EOS ?
   #   return error

   # feels like it.takewhile(lambda c: c != '<', iter(stream))
   # could work like this
   text|tag s k inc (acc -> acc') eos (k,v -> ...)=
     term, acc = take(pred andor term)

     if term then eos(k, a)

     inc(a) or ...

   # nope, try again

   parse-until! stream s, char c, premature(s,a -> ...), bool inclusive =
     match prem, a = take' (!= c) s
       true, _ -> premature(s, a)
       _ -> if incl
	       a + c
	      begin
		rewind(s, len(c))
		a
     take' pred stream =
       acc = ''
       while not eos stream
	 if not pred peek(stream)
	    acc += stream(1)
       return peek(stream) == '', acc

   # nope, does not typecheck, more again
   #   parse-until! returns premature : token(kind, acc) | acc
   #     it does too much, should only care about acc and stream
   #     parsing caller decides the token

   parse-until! s c incl =
     match p, a = take (!= c) s
      true, _ -> p, a
      false, _ ->
	  match incl
	    true -> p, a + c
	    _    -> p, a

   parse-until! s c incl =
     p, a = take (!= c) s
     return p, a + c if incl else p, a

   # Turns out to be problematic
   # Splitting logic with stream state and inclusive/exclusive
   # made me add stream.read(1) fix in non local places

* XML parser

** DONE Stream of inst | otag | etag | text | ... -> Tree

   stack shift reduce

   inst -> top.append it
   otag -> push (Tag. ...)
   text -> top.append it
   comm -> top.append it
   doct -> top.append it
   etag -> t = pop; top.append it

** DONE Bug: cycle in tree construction
   see commit e655648

** DONE Bug: non supported xml objects impedes reduction

   <!-- .... --> is seen as a tag, thus absorbs subsequent nodes,
   confusing the recursive logic.

   Better hypothesis: self-closing tags appending linearly since no
   etag to reduce.

   Solution: tokenizer could issue both ('otag', ...) then ('etag', ...)
   on the fly. *Tokenizing sugar*...

   Bug fixed (80% confidence)

** monadic parser ?

** objectional parser ?
   - no more explicit stateful stack recursion
   - A Root object walk the stream. On certain conditions, it
     will pass parsing to a new subclass (passing himself in need of
     recursion, REDUCE, SELF INSERT)

     Root.parse -> {...}, (Text | Inst | ...).parse -> ...
