
* Tokenizer

** DONE add comment support

** DONE add doctype support

** factor saxg code

   most sub generators are the same

** large test, OpenDocument sample (34KB)
   cv.xml

** DONE Bug: cv.xml uncovers an infinite loop in saxg

*** Trace. Warning, 98 lines

  in test_xml_cv
  in xml in root in inst in root in text in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in etag in root in otag in root in otag in root in etag in root
  in otag in root in otag in root in etag in root in otag in root in otag in root
  in etag in root in otag in root in otag in root in etag in root in etag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in etag in root in otag in root
  in otag in root in otag in root in otag in root in otag in root in otag in root
  in otag in root in otag in root in otag in root in otag in root in text in root
  in etag in root in etag in root in otag in root in otag in root in otag in root
  in otag in root in text in root in etag in root in otag in root in otag in root
  in text in root in etag in root in text in root in etag in root in otag in root
  in text in root in etag in root in etag in root in otag in root in otag in root 
  in etag in root in otag in root in etag in root in otag in root in otag in root 
  in otag in root in text in root in etag in root in otag in root in text in root 
  in etag in root in etag in root in otag in root in otag in root in otag in root 
  in otag in root in etag in root in otag in root in otag in root in etag in root 
  in otag in root in etag in root in otag in root in otag in root in otag in root 
  in text in root in otag in root in text in root in etag in root in etag in root 
  in etag in root in otag in root in otag in root in otag in root in otag in root 
  in otag in root in etag in root in otag in root in etag in root in otag in root 
  in otag in root in otag in root in text in root in etag in root in etag in root 
  in otag in root in otag in root in text in root in etag in root in otag in root 
  in text in root in etag in root in etag in root in otag in root in otag in root 
  in otag in root in otag in root in etag in root in otag in root in etag in root 
  in otag in root in otag in root in otag in root in text in root in etag in root 
  in etag in root in otag in root in otag in root in text in root in etag in root 
  in otag in root in text in root in etag in root in etag in root in otag in root 
  in otag in root in otag in root in otag in root in etag in root in otag in root 
  in etag in root in otag in root in otag in root in otag in root in text in root 
  in etag in root in etag in root in otag in root in otag in root in text in root 
  in etag in root in otag in root in text in root in etag in root in etag in root 
  in otag in root in otag in root in otag in root in otag in root in etag in root 
  in otag in root in etag in root in otag in root in otag in root in otag in root 
  in text in root in otag in root in text in root in etag in root in text in root 
  in otag in root in text in root in etag in root in etag in root in etag in root 
  in otag in root in otag in root in otag in root in otag in root in otag in root 
  in otag in root in etag in root in etag in root in otag in root in otag in root 
  in otag in root in otag in root in text in root in etag in root in etag in root 
  in etag in root in otag in root in otag in root in otag in root in text in root 
  in etag in root in otag in root in text in root in etag in root in etag in root 
  in otag in root in otag in root in text in root in etag in root in etag in root 
  in otag in root in otag in root in otag in root in text in root in etag in root 
  in etag in root in etag in root in etag in root in otag in root in otag in root 
  in otag in root in otag in root in otag in root in etag in root in etag in root 
  in otag in root in otag in root in otag in root in text in root in etag in root 
  in etag in root in otag in root in otag in root in text in root in etag in root 
  in otag in root in text in root in etag in root in etag in root in otag in root 
  in otag in root in otag in root in otag in root in otag in root in etag in root 
  in etag in root in otag in root in otag in root in otag in root in text in root 
  in etag in root in etag in root in otag in root in otag in root in text in root 
  in etag in root in otag in root in text in root in etag in root in otag in root 
  in otag in root in text in root in etag in root in etag in root in etag in root 
  in otag in root in otag in root in otag in root in otag in root in otag in root 
  in etag in root in etag in root in otag in root in otag in root in otag in root 
  in text in root in etag in root in etag in root in otag in root in otag in root 
  in text in root in etag in root in otag in root in text in root in etag in root 
  in otag in root in text in root in etag in root in otag in root in otag in root 
  in peek

*** Fix: sys.setrecursionlimit(2000)
    cv.xml prints.

    Need to rewrite as a single while True: generator ?

* XML parser

** DONE Stream of inst | otag | etag | text | ... -> Tree

   stack shift reduce

   inst -> top.append it
   otag -> push (Tag. ...)
   text -> top.append it
   comm -> top.append it
   doct -> top.append it
   etag -> t = pop; top.append it

** DONE Bug: cycle in tree construction
   see commit e655648

** DONE Bug: non supported xml objects impedes reduction

   <!-- .... --> is seen as a tag, thus absorbs subsequent nodes,
   confusing the recursive logic.

   Better hypothesis: self-closing tags appending linearly since no
   etag to reduce.

   Solution: tokenizer could issue both ('otag', ...) then ('etag', ...)
   on the fly. *Tokenizing sugar*...

   Bug fixed (80% confidence)

** monadic parser ?

** objectional parser ?
   - no more explicit stateful stack recursion
   - A Root object walk the stream. On certain conditions, it
     will pass parsing to a new subclass (passing himself in need of
     recursion, REDUCE, SELF INSERT)

     Root.parse -> {...}, (Text | Inst | ...).parse -> ...

