- name: actions-pytest
  # You may pin to the exact commit or the version.
  # uses: xoviat/actions-pytest@6e27d0810b47a907cc45bc96092599f072b28870
  uses: xoviat/actions-pytest@0.1-alpha2
  with:
    # Arguments for the pytest command
    verbose: true
    emoji: true
    job-summary: true
    # custom-arguments: '-q'
    click-to-expand: true
    report-title: 'Test Report (sax)'
